name: Deploy Backend

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m

          script: |
            set -e

            cd ~/Micro-URL-Backend

            git fetch origin
            git reset --hard origin/main

            docker compose up -d --build --remove-orphans

            docker image prune -af